### ISSUE TITLE
[Bug]: Publishing config doesn't work

### ISSUE THREAD

**Issue by Restingo** [huynt57/laravel-optimize-init-db-connection#1]
### What happened?

When using command

`php artisan vendor:publish --tag="laravel-optimize-init-db-connection-config"`

result is

`INFO  No publishable resources for tag [laravel-optimize-init-db-connection-config].`

### How to reproduce the bug

Use command

`php artisan vendor:publish --tag="laravel-optimize-init-db-connection-config"`

### Package Version

1.0

### PHP Version

8.1.13

### Laravel Version

10.44.0

### Which operating systems does with happen with?

Windows, Linux

**Comment by mikelito859** [comment]
Same here

**Comment by huynt57** [comment]
I updated the command to: php artisan vendor:publish --tag="optimize-init-db-connection-config". Sorry for typo
